### ISSUE TITLE
Unexcepted no bssid_or_ssid 

### ISSUE THREAD

**Issue by hamabao413** [nothingbutlucas/pwnagotchi_fast_dictionary#1]
I got [FAST_DICTIONARY] Unexpected error: 'FastDictionary' object has no attribute 'find_ssid_and_bssid' 
Is anything I did err?

**Comment by nothingbutlucas** [comment]
Hi there!, thank you for opening an issue!
Yes, you are right. I forgot to remove the `self` when I removed the functions from the class.
Thanks for noticing, it should be fixed now.
